# Generated by Django 5.0.4 on 2024-05-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم العميل'),
        ),
    ]
